# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  who:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  time: # id of output
    description: 'The time we greeted you'
  files:
    description: 'ls command'
runs:
  using: 'composite'
  steps:
    - name: Run entrypoint
      run: bash entrypoint.sh
      shell: bash
      args:
        - ${{ inputs.who-to-greet }}
    - name: Post run
      if: always()
      run: echo "post run hello world :D"
      shell: bash
