on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    name: A job to say hello
    steps:
      - uses: actions/checkout@v3
      - name: Hello world action step
        id: hello
        uses: TechWiz-3/test-gh-action@v0.0.2  # hello?
        with:
          who-to-greet: 'Z the G'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
